project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - report.qmd
    - full-analysis.qmd
  resources:
    - Attachments/**

website:
  title: "Analytics for eLife revision"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: report.qmd
        text: Report
      - href: full-analysis.qmd
        text: Full analysis

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 5
    toc-title: Contents
    code-fold: true

lang: en
